---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers
    apt:
      name: apache2
      state: present

  - name: copy index.je file into all nodes
    template:
      src:
      dest: /var/www/html/index.html



     
    
  
  